---
- name: Centos package installation
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - selinux-policy-targeted
    - selinux-policy
    - selinux-policy-base

- name: install the docker ce stable via yum-config-manager
  command: yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker and update cache
  yum:
    name: docker-ce
    update_cache: yes
    state: present
