---
- name: Linux Mint package installation
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - add-apt-key

- name: add the docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: force add the stable channel
  shell: /usr/bin/add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(sed 's/\/.*//' /etc/debian_version | sed 's/\..*//') stable"

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
