---
- name: APT; remove packaged versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ PACKAGE_RETRIES }}"
  delay: "{{ PACKAGE_DELAY }}"

- name: APT; Ubuntu package installation
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - add-apt-key
      - gnupg-agent
    state: latest
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ PACKAGE_RETRIES }}"
  delay: "{{ PACKAGE_DELAY }}"

- name: APT_KEY; add the docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: APT_REPOSITORY; force add the stable channel
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker-ce
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ PACKAGE_RETRIES }}"
  delay: "{{ PACKAGE_DELAY }}"
