---
# TODO: check distribution and version and fail if not valid

- name: fail if not Ubuntu or Centos
  fail: 
    msg: "This role currently only support Ubuntu and CentOS"
  when: ansible_distribution != "Ubuntu" and ansible_distribution != "CentOS"

- name: fail if Ubuntu and not Ubuntu 14+
  fail: 
    msg: "This role currently only support Ubuntu 14+"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 14

- name: fail if CentOS, and not RHEL 7+
  fail: 
    msg: "This role currently only support Centos 6+"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int < 7

# tasks file for ansible-docker
- name: execute distribution specific tasks
  include: "{{ ansible_distribution }}.yml"
