---
# TODO: check distribution and version and fail if not valid

- name: test the distribution
  fail: 
    msg: "This role currently only support Ubuntu and CentOS"
  when: ansible_distribution != "Ubuntu" and ansible_distribution != "CentOS"

- name: if Ubuntu, test version
  fail: 
    msg: "This role currently only support Ubuntu 14+"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 14

- name: if CentOS, test version
  fail: 
    msg: "This role currently only support Centos 6+"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 6

# tasks file for ansible-docker
- name: execute distribution specific tasks
  include: "{{ ansible_distribution }}.yml"
