---
- name: Ubuntu package installation
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add the docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: force add the stable channel
  shell: /usr/bin/add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(/usr/bin/lsb_release -cs) stable"

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
